services:
  dashboard:
    container_name: ticket-dashboard
    restart: unless-stopped
    networks:
      - ticket-network
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_WS_URL=${VITE_WS_URL}
    ports:
      - "3000:80"

networks:
  ticket-network:
    name: ticket-network
    external: true
